window.onload=initUser();
 function initUser(){        
		function jsuserR0(){
		   document.getElementById("jsartright0").style.display="block";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR1(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="block";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR2(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="block";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR3(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="block";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR4(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="block";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR5(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="block";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR6(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="block";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR7(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="block";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR8(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="block";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR9(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="block";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR10(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="block";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR11(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="block";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR12(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="block";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR13(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="block";
		   document.getElementById("jsartright14").style.display="none";
		  }
	    function jsuserR14(){
		   document.getElementById("jsartright0").style.display="none";
		   document.getElementById("jsartright1").style.display="none";
		   document.getElementById("jsartright2").style.display="none";
		   document.getElementById("jsartright3").style.display="none";
		   document.getElementById("jsartright4").style.display="none";
		   document.getElementById("jsartright5").style.display="none";
		   document.getElementById("jsartright6").style.display="none";
		   document.getElementById("jsartright7").style.display="none";
		   document.getElementById("jsartright8").style.display="none";
		   document.getElementById("jsartright9").style.display="none";
		   document.getElementById("jsartright10").style.display="none";
		   document.getElementById("jsartright11").style.display="none";
		   document.getElementById("jsartright12").style.display="none";
		   document.getElementById("jsartright13").style.display="none";
		   document.getElementById("jsartright14").style.display="block";
		  }
}		  